# file for testing https requests for trips and types

@base_url = http://localhost:8080/fiftygo
@jwt = eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJmaWZ0eWdvIiwic3ViIjoianNtaXRoMiIsImF1dGhvcml0aWVzIjoiUk9MRV9QUkVNSVVNIiwiZXhwIjoxNjYxMzY4NDQ0fQ.PMkWxrbOX_TIrStap9ELXK_EtKjxt-3PW9H1jzbRd9c


### technically, get an authorization JWT token (basically, log in)
POST http://localhost:8080/authenticate HTTP/1.1
Content-Type: application/json

{
    "username": "jsmith2",
    "password": "P@ssw0rd!"
}





## TRIPS

### GET all trips, using authorization
GET {{base_url}}/trip HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{jwt}}

### GET all trips by user ID, using authorization
GET {{base_url}}/trip/2 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{jwt}}

## GET a trip by ID
GET {{base_url}}/trip/3 HTTP/1.1
Content-Type: application/json

### POST a trip, using authorization
POST {{base_url}}/trip HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "tripDescription": "test description",
    "tripStartDate": "2023-09-15",
    "tripEndDate": "2023-09-20",
    "transportation": "bus",
    "tripPriority": 3,
    "tripDidIt": false,
    "userId": 1,
    "pin": {
        "pinDescription": "Test!",
        "pinDate": "2022-10-31",
        "pinPriority": 1,
        "pinDidIt": false,
        "city": {
            "cityId": 1630035577,
            "cityName": "San Juan",
            "stateAbr": "PR",
            "stateName": "Puerto Rico",
            "cityLatitude": "18.3985",
            "cityLongitude": "-66.0610"
        },
        "type": {
            "typeId": 26,
            "typeName": "ski"
        }
    }
}

### PUT a trip, using authorization
PUT {{base_url}}/trip/2 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "tripId": 2,
    "tripStartDate": "2023-10-15",
    "tripEndDate": "2023-10-20"
}

### DELETE a trip, using authorization
DELETE http://localhost:8080/sighting/3 HTTP/1.1
Authorization: Bearer {{jwt}}





## TYPES

### GET all types
GET {{base_url}}/type HTTP/1.1
Content-Type: application/json

## GET a type by ID
GET {{base_url}}/type/3 HTTP/1.1
Content-Type: application/json

### POST a type, using authorization
POST {{base_url}}/type HTTP/1.1
Content-Type: application/json

{
   "typeName": "ski"
}

### PUT a type, using authorization
PUT {{base_url}}/type/2 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "typeName": "sky dive"
}

### DELETE a type
DELETE http://localhost:8080/sighting/1 HTTP/1.1