# file for testing HTTP requests!

@base_url = http://localhost:8080/fiftygo
@jwt = eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJmaWZ0eWdvIiwic3ViIjoianNtaXRoMSIsImF1dGhvcml0aWVzIjoiUk9MRV9BRE1JTiIsImFwcFVzZXJJZCI6MSwiZmlyc3ROYW1lIjoiSm9obiIsImxhc3ROYW1lIjoiU21pdGgiLCJleHAiOjE2NjE5MjI5MzB9.vkIUzY84ez4SRDw3zYOzaNHXWZrmfanP6_ILP9cTRws


### technically, get an authorization JWT token (basically, log in)
POST http://localhost:8080/authenticate HTTP/1.1
Content-Type: application/json

{
    "username": "jsmith1",
    "password": "P@ssw0rd!"
}

### create an account. If it worked, then "login" below
POST http://localhost:8080/create_account HTTP/1.1
Content-Type: application/json

{
    "firstName": "Kelie",
    "lastName": "Berendt",
    "username": "kberendt",
    "password": "P@ssw0rd!"
}

### technically, get an authorization JWT token (basically, log in)
POST http://localhost:8080/authenticate HTTP/1.1
Content-Type: application/json

{
    "username": "kberendt",
    "password": "P@ssw0rd!"
}

### GET all Pins, using authorization
GET {{base_url}}/pin HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{jwt}}

### POST a new Pin, using authorization
POST {{base_url}}/pin HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "pinDescription": "Test!",
    "pinDate": "2022-10-31",
    "pinPriority": 1,
    "pinDidIt": false,
    "cityId": 1630035577,
    "typeId": 26,
    "appUserId": 1
}

### PUT (update) an existing Pin, using authorization
PUT {{base_url}}/pin/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "pinId": 1,
    "pinDescription": "Testing PUT1!",
    "pinDate": "2022-10-31",
    "pinPriority": 1,
    "pinDidIt": false,
    "cityId": 1630035577,
    "typeId": 26,
    "appUserId": 1
}


### GET Pin by ID, using authorization
GET {{base_url}}/pin/1 HTTP/1.1
Authorization: Bearer {{jwt}}

### DELETE Pin by ID, using authorization
DELETE {{base_url}}/pin/1 HTTP/1.1
Authorization: Bearer {{jwt}}

### GET pin by UserID, using authorization
GET {{base_url}}/pin/user/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{jwt}}

### GET all types, using authorization
GET {{base_url}}/type HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{jwt}}

### GET all trips, using authorization
GET {{base_url}}/trip HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{jwt}}

### GET all trips by userId, using authorization
GET {{base_url}}/trip/user/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{jwt}}

### POST a trip, using authorization
POST {{base_url}}/trip HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "tripDescription": "test",
    "tripStartDate": "2023-10-31",
    "tripEndDate": "2023-11-15",
    "transportation": "car",
    "tripPriority": 1,
    "tripDidIt": "false",
    "appUserId": 1
}

### GET all cities, using authorization
GET {{base_url}}/city HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{jwt}}

### PUT (update) AppUser, using authorization
PUT http://localhost:8080/user/4 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "appUserId": "4",
    "firstName": "Kelie",
    "lastName": "TestUpdate-Berendt",
    "username": "kberendt",
    "password": "P@ssw0rd!"
}

### GET all users using ADMIN authorization only
GET http://localhost:8080/user HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{jwt}}

### GET all cities by state using authorization
GET {{base_url}}/city/state/WI HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{jwt}}

### GET all cities that match search, using authorization
GET {{base_url}}/city/1840003046 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{jwt}}

### GET all types that match search, using authorization
GET {{base_url}}/type/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{jwt}}


### GET all States as a list in order with no duplicates:
GET {{base_url}}/city/states HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{jwt}}

### add a pin(5) to a trip(3)
POST {{base_url}}/trip/addpin HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "pinId": 5,
    "tripId": 3
}

### GET that trip by ID to check, using authorization
GET {{base_url}}/trip/3 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{jwt}}