# file for testing HTTP requests!

@base_url = http://localhost:8080/fiftygo
@jwt = eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJmaWZ0eWdvIiwic3ViIjoianNtaXRoMiIsImF1dGhvcml0aWVzIjoiUk9MRV9QUkVNSVVNIiwiZXhwIjoxNjYxMzYyMDE5fQ.3uNssRuoZJgWoIoz-xTGOlfWU5LwV5o-HpmIrC-qfUU


### technically, get an authorization JWT token (basically, log in)
POST http://localhost:8080/authenticate HTTP/1.1
Content-Type: application/json

{
    "username": "jsmith2",
    "password": "P@ssw0rd!"
}

### GET all pins, using authorization
GET {{base_url}}/pin HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{jwt}}

### POST, using authorization
POST {{base_url}}/pin HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "pinDescription": "Test!",
    "pinDate": "2022-10-31",
    "pinPriority": 1,
    "pinDidIt": false,
    "city": {
        "cityId": 1630035577,
        "cityName": "San Juan",
        "stateAbr": "PR",
        "stateName": "Puerto Rico",
        "cityLatitude": "18.3985",
        "cityLongitude": "-66.0610"
    },
    "type": {
        "typeId": 26,
        "typeName": "ski"
    },
    "userId": 1
}



### GET pin by ID, using authorization
GET {{base_url}}/pin/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{jwt}}

### GET all types, using authorization
GET {{base_url}}/type HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{jwt}}

### GET all trips, using authorization
GET {{base_url}}/trip HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{jwt}}

### POST a trip, using authorization
POST {{base_url}}/trip HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "tripDescription": "test",
    "tripStartDate": "2023-10-31",
    "tripEndDate": "2023-11-15",
    "transportation": "car",
    "tripPriority": 1,
    "tripDidIt": "false",
    "userId": 1,
}