# file for testing HTTP requests!

###
POST http://localhost:8080/authenticate HTTP/1.1
Content-Type: application/json

{
    "username": "jsmith2",
    "password": "P@ssw0rd!"
}

### authorization (got a license for that request??)
POST http://localhost:8080/pin HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJmaWZ0eWdvIiwic3ViIjoianNtaXRoMiIsImF1dGhvcml0aWVzIjoiUk9MRV9QUkVNSVVNIiwiZXhwIjoxNjYxMzE4NTI1fQ.NXmxt2z5hO_Mhq8JNVP-sUS861OQZtYO9caOzpakJXI

{
    "pinDescription": "Test!",
    "pinDate": "2022-10-31",
    "pinPriority": 1,
    "pinDidIt": false,
    "city": {
        "cityId": 1630035577,
        "cityName": "San Juan",
        "stateAbr": "PR",
        "stateName": "Puerto Rico",
        "cityLatitude": 18.3985,
        "cityLongitude": -66.0610
    },
    "type": {
        "typeId": 1,
        "typeName": "bike"
    },
    "userId": 1
}